services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plantis
    ports:
      - "5432:5432"
    volumes:
      - plantis_db:/var/lib/postgresql/data

volumes:
  plantis_db:
